const data = {
  products: [
    {
      _id: "1",
      name: "Turtle Cotton Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Turtle",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Allen Solly Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 98,
      brand: "Allon Solly",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Raymond Pant",
      category: "Trousers",
      image: "/images/p3.jpg",
      price: 150,
      brand: "Raymond",
      rating: 4.8,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Lee-Cooper trouser",
      category: "Trousers",
      image: "/images/p4.jpg",
      price: 190,
      brand: "Lee_Cooper",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Titan Watch",
      category: "Watches",
      image: "/images/p5.jpg",
      price: 400,
      brand: "Titan",
      rating: 4.8,
      numReviews: 50,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Zara Cotton Shirt",
      category: "Shirts",
      image: "/images/p6.jpg",
      price: 500,
      brand: "Zara",
      rating: 4.9,
      numReviews: 109,
      description: "high quality product",
    },
  ],
};

export default data;
